### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [JCatwood/VeccTMVN#4]
I suggest adding the topics `r-package`, `statistics`, `normal-distribution`, `probability-distribution` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by JCatwood** [comment]
Thanks for the advice. Sorry for the delay. The changes have been made.
